export const GET_FILMS_BEGIN = 'GET_FILMS_BEGIN'
export const GET_FILMS_SUCCESS = 'GET_FILMS_SUCCESS'
export const GET_FILMS_FAIL = 'GET_FILMS_FAIL'

export const GET_FILM_EPISODES_BEGIN = 'GET_FILM_EPISODES_BEGIN'
export const GET_FILM_EPISODES_SUCCESS = 'GET_FILM_EPISODES_SUCCESS'
export const GET_FILM_EPISODES_FAIL = 'GET_FILM_EPISODES_FAIL'

export const SAVE_FILM = 'SAVE_FILM'

